Update README.md
modolee/add-env-to-gae-conf pull request #4
Opened 2020-10-30 08:45 UTC by andylang8445

2020-10-30 09:16 UTC, modolee requested changes
우선 PR 날려 주셔서 감사합니다.
다만 제가 설명을 부족하게 달아 놓은 탓에 엉뚱한 방향으로 수정이 된 것 같습니다.
해당 부분만 다시 수정 부탁드립니다.
하나 더 있는 PR의 경우도 마찬가지로 envsub에 대한 설명이 아니기 때문에 반려하도록 하겠습니다.

감사합니다.

2020-10-30 09:16 UTC, modolee commented on README.md
> +## What is envsub?
설명이 부족했던 것 같습니다. README에 적혀 있는 설명은 envsub에 대한 내용이 아니라 제가 작성한 쉘 스크립트에 대한 내용입니다. 그런데 해당 스크립트를 보완할 수 있는 라이브러리를 찾아서 최상단에 내용을 추가한 것입니다.

2020-10-30 09:16 UTC, modolee commented on README.md
> +## How do I use envsub?
이것 역시 envsub에 대한 내용이 아닙니다.

2020-10-31 00:59 UTC, merged

2020-10-31 04:22 UTC, andylang8445 commented on README.md
> +## How do I use envsub?
방금 새로운 PR을 날렸는데 혹시 그것은 내용에 부합하는지 알 수 있을까요?